"""
Django settings for TRAK_Backend project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-pu50tf0wn-ug=15%$i9_^7dune*_q5wff%w&&4h6pi3!5n(7b#",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")

_allowed = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").strip()
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()]

AUTH_USER_MODEL = "accounts.User"

# Comma-separated emails → role admin on registration.
# Three built-in admins (Danyal, Shahroz, Abdullah) are always included; extend with ADMIN_EMAILS.
_BUILTIN_ADMIN_EMAILS = (
    "danyal@admin.com,shahroz@admin.com,abdullah@admin.com"
)
# Used by seed_default_admins only (shared initial password).
BUILTIN_ADMIN_EMAILS_LIST = [
    e.strip().lower() for e in _BUILTIN_ADMIN_EMAILS.split(",") if e.strip()
]
_extra_admin_emails = os.environ.get("ADMIN_EMAILS", "").strip()
ADMIN_EMAILS = (
    f"{_BUILTIN_ADMIN_EMAILS},{_extra_admin_emails}"
    if _extra_admin_emails
    else _BUILTIN_ADMIN_EMAILS
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Project apps
    'accounts.apps.AccountsConfig',
    'news.apps.NewsConfig',
    'notifications.apps.NotificationsConfig',
    'admin_panel.apps.AdminPanelConfig',
    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'channels',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TRAK_Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TRAK_Backend.wsgi.application'
ASGI_APPLICATION = "TRAK_Backend.asgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

_db_engine = os.environ.get("DJANGO_DB_ENGINE", "sqlite3").strip().lower()
if _db_engine == "djongo":
    DATABASES = {
        "default": {
            "ENGINE": "djongo",
            "NAME": os.environ.get("DJANGO_DB_NAME", "TRAK_DB"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / os.environ.get("DJANGO_SQLITE_NAME", "db.sqlite3"),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "EXCEPTION_HANDLER": "TRAK_Backend.api_exceptions.custom_exception_handler",
    "DEFAULT_THROTTLE_RATES": {
        "register": os.environ.get("THROTTLE_REGISTER", "10/hour"),
        "login": os.environ.get("THROTTLE_LOGIN", "30/hour"),
        "refresh": os.environ.get("THROTTLE_REFRESH", "120/hour"),
        "password_reset": os.environ.get("THROTTLE_PASSWORD_RESET", "5/hour"),
    },
}

CORS_ALLOW_ALL_ORIGINS = os.environ.get(
    "CORS_ALLOW_ALL_ORIGINS",
    "true" if DEBUG else "false",
).lower() in (
    "1",
    "true",
    "yes",
)
_cors_origins = os.environ.get("CORS_ALLOWED_ORIGINS", "").strip()
if _cors_origins:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(",") if o.strip()]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.environ.get("JWT_ACCESS_MINUTES", "60"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.environ.get("JWT_REFRESH_DAYS", "7"))
    ),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

_redis_url = os.environ.get("REDIS_URL", "").strip()
if _redis_url:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [_redis_url]},
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }

ALLOW_DEMO_SOCIAL_LOGIN = os.environ.get("ALLOW_DEMO_SOCIAL_LOGIN", "false").lower() in ("1", "true", "yes")

# --- Email (password reset). Dev default: print emails to console. ---
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() in ("1", "true", "yes")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "TRAK <noreply@trak.local>")
# Full URL to the web (or universal) reset screen, e.g. https://app.example.com/reset-password
PASSWORD_RESET_FRONTEND_URL = os.environ.get(
    "PASSWORD_RESET_FRONTEND_URL",
    "http://127.0.0.1:5173/reset-password",
).strip()
SOCIAL_AUTH_FRONTEND_URL = os.environ.get(
    "SOCIAL_AUTH_FRONTEND_URL",
    "http://127.0.0.1:5173/login",
).strip()

# OAuth providers
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "").strip()
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET", "").strip()
GOOGLE_REDIRECT_URI = os.environ.get(
    "GOOGLE_REDIRECT_URI",
    "http://127.0.0.1:8000/api/auth/social/google/callback/",
).strip()
GITHUB_CLIENT_ID = os.environ.get("GITHUB_CLIENT_ID", "").strip()
GITHUB_CLIENT_SECRET = os.environ.get("GITHUB_CLIENT_SECRET", "").strip()
GITHUB_REDIRECT_URI = os.environ.get(
    "GITHUB_REDIRECT_URI",
    "http://127.0.0.1:8000/api/auth/social/github/callback/",
).strip()

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    if os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "true").lower() in ("1", "true", "yes"):
        SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = (
        os.environ.get("SECURE_HSTS_INCLUDE_SUBDOMAINS", "true").lower() in ("1", "true", "yes")
    )
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_REFERRER_POLICY = os.environ.get("SECURE_REFERRER_POLICY", "same-origin")

# --- Raw news scrapers (pymongo collection `raw_articles` in TRAK_DB) ---
MONGODB_URI = os.environ.get("MONGODB_URI", "mongodb://127.0.0.1:27017/")
MONGODB_RAW_DATABASE = os.environ.get("MONGODB_RAW_DATABASE", "TRAK_DB")
MONGODB_RAW_COLLECTION = os.environ.get("MONGODB_RAW_COLLECTION", "raw_articles")
MONGODB_PROCESSED_COLLECTION = os.environ.get("MONGODB_PROCESSED_COLLECTION", "processed_articles")
MONGODB_USER_KEYWORDS_COLLECTION = os.environ.get("MONGODB_USER_KEYWORDS_COLLECTION", "user_keywords")
MONGODB_CHATBOT_HISTORY_COLLECTION = os.environ.get("MONGODB_CHATBOT_HISTORY_COLLECTION", "chatbot_history")
MONGODB_NOTIFICATIONS_COLLECTION = os.environ.get("MONGODB_NOTIFICATIONS_COLLECTION", "notifications")
MONGODB_DEVICE_TOKENS_COLLECTION = os.environ.get("MONGODB_DEVICE_TOKENS_COLLECTION", "device_tokens")
MONGODB_USER_PREFERENCES_COLLECTION = os.environ.get("MONGODB_USER_PREFERENCES_COLLECTION", "user_preferences")
MONGODB_BOOKMARKS_COLLECTION = os.environ.get("MONGODB_BOOKMARKS_COLLECTION", "bookmarks")
MONGODB_REACTIONS_COLLECTION = os.environ.get("MONGODB_REACTIONS_COLLECTION", "reactions")

# Optional: directory with HuggingFace-style saved model for 3-class credibility (real/fake/suspicious)
CREDIBILITY_MODEL_PATH = os.environ.get("CREDIBILITY_MODEL_PATH", "").strip() or None
CREDIBILITY_CONFIDENCE_THRESHOLD = float(os.environ.get("CREDIBILITY_CONFIDENCE_THRESHOLD", "0.6"))

# Many news sites sit behind CDNs that block non-browser user-agents. Use a real
# browser token plus a project suffix so traffic is identifiable.
SCRAPER_USER_AGENT = os.environ.get(
    "SCRAPER_USER_AGENT",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 TRAK-NewsIngest/1.0",
)
SCRAPER_DELAY_SECONDS = float(os.environ.get("SCRAPER_DELAY_SECONDS", "2.5"))
SCRAPER_REQUEST_TIMEOUT = float(os.environ.get("SCRAPER_REQUEST_TIMEOUT", "30"))
SCRAPER_MAX_HTML_BYTES = int(os.environ.get("SCRAPER_MAX_HTML_BYTES", "5_000_000"))  # 5 MB cap per page

# Keep full page HTML in MongoDB in addition to extracted fields (large; default off).
SCRAPER_STORE_RAW_HTML = os.environ.get("SCRAPER_STORE_RAW_HTML", "false").lower() in (
    "1",
    "true",
    "yes",
)

# RSS feeds: merged with `news/scrapers/sources_catalog.py` → RSS_FEED_URLS (add feeds there first).
SCRAPER_RSS_FEED_URLS = [
    u.strip()
    for u in os.environ.get("SCRAPER_RSS_FEED_URLS", "").split(",")
    if u.strip()
]

# Generic CSS-based sites: merged with `sources_catalog.py` → GENERIC_SITES.
SCRAPER_GENERIC_SOURCES = []

# Path to JSON file (list of site configs, or {"sites": [...]}) relative to BASE_DIR if not absolute.
SCRAPER_GENERIC_SOURCES_JSON = os.environ.get("SCRAPER_GENERIC_SOURCES_JSON", "").strip() or None
