# Generated by Django 5.2.14 on 2026-05-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_email_verification_otp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='accounts_em_email_7bfcfb_idx',
            old_name='accounts_em_email_p_8a1f2d_idx',
        ),
    ]
